[package]
name = "helix"
version = "0.1.0"
authors = ["Ravi Shankar <wafflespeanut@gmail.com>"]

[dependencies.fillings]
path = "src/rust-fillings"
version = "0.1"

[dependencies]
lazy_static = "0.1"
num-traits = "0.1"
rand = "0.3"
rustc-serialize = "0.3"
bit-vec = "0.4"
