[package]
name = "helix"
version = "0.1.0"
authors = ["Ravi Shankar <wafflespeanut@gmail.com>"]

[dependencies]
num-traits = "0.1"
rustc-serialize = "0.3"
bit-vec = "0.4"

[dev-dependencies]
lazy_static = "0.1"
rand = "0.3"
